references:
  commands:
    install_awscli: &install_awscli
      command: |
        apk --update add curl python jq bash
        curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
        python get-pip.py
        pip install awscli
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile circleci-ecs
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile circleci-ecs
    defaults: &defaults
      docker:
        - image: docker:18.06.0
      working_directory: ~/workspace

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/smartmat.jp:$CIRCLE_SHA1 .
      - run: *install_awscli
      - run: chmod +x ./deploy.sh
      - run: sh ./deploy.sh


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
