references:
  commands:
    install_awscli: &install_awscli
      command: |
        apk --update add curl python jq bash
        curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
        python get-pip.py
        pip install awscli
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile circleci-ecs
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile circleci-ecs
    defaults: &defaults
      docker:
        - image: docker:18.06.0
      working_directory: ~/workspace

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      - AWS_REGION: ap-northeast-1
      - AWS_S3_BUCKET: smartmat-docker
      - AWS_CODEDEPLOY_APPLICATION_NAME: smartmat-app
      - AWS_CODEDEPLOY_DEPLOYMENT_GROUP: smartmat-deploy-group
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_awscli
      - run:
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/smartmat.jp:$CIRCLE_SHA1 ./docker
            docker save $AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/smartmat.jp:$CIRCLE_SHA1 > docker/image.tar

            sed -i -e 's/^CIRCLE_SHA1=.*/CIRCLE_SHA1='$CIRCLE_SHA1'/g' docker/scripts/start.sh
            sed -i -e 's@image: \$.*@image: '$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/smartmat.jp:'$CIRCLE_SHA1'@g' docker/docker-compose.yml

            aws s3 rm s3://${AWS_S3_BUCKET}/app/ --recursive
            aws --region ${AWS_REGION} deploy push --application-name ${AWS_CODEDEPLOY_APPLICATION_NAME} --s3-location s3://${AWS_S3_BUCKET}/app/${CIRCLE_SHA1}.tar.gz --source ./docker

            aws --region ${AWS_REGION} s3api wait object-exists --bucket ${AWS_S3_BUCKET} --key app/${CIRCLE_SHA1}.tar.gz
            aws --region ${AWS_REGION} deploy create-deployment --application-name ${AWS_CODEDEPLOY_APPLICATION_NAME} --deployment-group-name ${AWS_CODEDEPLOY_DEPLOYMENT_GROUP} --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=${AWS_S3_BUCKET},key=app/${CIRCLE_SHA1}.tar.gz,eTag=$( aws s3api head-object --bucket ${AWS_S3_BUCKET} --key app/${CIRCLE_SHA1}.tar.gz --query 'ETag' --output text | sed 's/^"\(.*\)"$/\1/' ),bundleType=zip --ignore-application-stop-failures

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-codedeploy
